name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install yajl-tools
        run: sudo apt-get install -qq yajl-tools

      - name: Check that the list is valid JSON
        run: json_verify < $GITHUB_WORKSPACE/data/whitelist.json
